all: matrixmul_case_a matrixmul_case_b matrixmul_case_c

matrixmul_case_a: matrixmul_case_a.c
	gcc -o matrixmul_case_a matrixmul_case_a.c -fopenmp

matrixmul_case_b: matrixmul_case_b.c
	gcc -o matrixmul_case_b matrixmul_case_b.c -fopenmp

matrixmul_case_c: matrixmul_case_c.c
	gcc -o matrixmul_case_c matrixmul_case_c.c -fopenmp
