all: puzzle_a puzzle_b

puzzle_a: puzzle_a.c hashtable.c priority_queue.c
	gcc -o puzzle_a puzzle_a.c hashtable.c priority_queue.c -lpthread

puzzle_b: puzzle_b.c hashtable.c priority_queue.c
	gcc -o puzzle_b puzzle_b.c hashtable.c priority_queue.c -lpthread
